apiVersion: v1
kind: Service
metadata:
  name: headroom
  namespace: zet
  labels:
    app: headroom
spec:
  type: ClusterIP
  selector:
    app: headroom
  ports:
    - name: http
      port: 8787
      targetPort: http
      protocol: TCP
